apiVersion: v1
kind: ConfigMap
metadata:
  name: sws
  labels:
    app: sws
data:
  config.yaml: |
    server:
      port: 20001
      static_content_root_directory: /opt/sws/console
      credentials:
        username: jdoe
        password: password
